# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_password: <%= ENV["MANDRILL_API_KEY"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  domain_name: example.com
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  secret_key_base: 1f25df335b3da9b7abfedb929c5473b2e0efda4b58c4ecbe762e9f1f5d378c27b0130c5322102014830ea2b99f9278fbeba49c5720ad8eb893ff42131fa7e209

test:
  secret_key_base: 84136fcdcec5c31cb2eaa0623f2d60c5f53132d59ea09eff2fbc2d847cccd2df5731aedadd6699960845786c7ce328046e0919f6a663cc34b4a04f287d4dd65d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_password: <%= ENV["MANDRILL_API_KEY"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  domain_name: example.com
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
